services:
  satis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: satis
    volumes:
      - "${COMPOSER_HOME:-$HOME/.composer}:/composer"
      - ./bin/satis:/satis/bin/satis
      - ./satis.json:/satis.json
      - ./output:/output
      - ./logs:/var/log

  web:
    image: nginx:latest
    container_name: satis_webserver
    ports:
      - "${SATIS_PORT:-9000}:80"
    volumes:
      - ./.htpasswd:/etc/nginx/.htpasswd
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./output:/usr/share/nginx/html:ro # Serve the Satis output directory
    restart: unless-stopped
